### ISSUE TITLE
Can not open the market GUI.

### ISSUE THREAD

**Issue by zsn741656478** [Xwaffle1/UniversalMarket#20]
https://i.loli.net/2019/06/16/5d05e0055d8c713813.png
This is ERROR.

**Comment by VOrlando520** [comment]
Can also verify this error. Seems to be happening to any server that is using newer builds of SpongeForge

**Comment by hilookas** [comment]
Same problem.
minecraft 1.12.2 forge 1.23.5.2825 sponge 1.12.2-2825-7.1.6

```
[Server thread/ERROR] [Sponge]: Error occurred while executing command 'um' for source EntityPlayerMP['lookas2001'/248, l='world', x=302.00, y=64.00, z=229.00]: There's no NBT Data set in the provided container
org.spongepowered.api.data.persistence.InvalidDataException: There's no NBT Data set in the provided container
	at net.minecraft.item.ItemStack.setRawData(ItemStack.java:2534) ~[aip.class:?]
	at com.xwaffle.universalmarket.utils.ItemBuilder.<init>(ItemBuilder.java:38) ~[ItemBuilder.class:?]
	at com.xwaffle.universalmarket.utils.ItemBuilder.<init>(ItemBuilder.java:31) ~[ItemBuilder.class:?]
	at com.xwaffle.universalmarket.market.Market.openMarket(Market.java:247) ~[Market.class:?]
	at com.xwaffle.universalmarket.market.Market.openMarket(Market.java:167) ~[Market.class:?]
	at com.xwaffle.universalmarket.commands.MarketCommand.process(MarketCommand.java:45) ~[MarketCommand.class:?]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2825-7.1.6]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337) [SpongeCommandManager.class:1.12.2-2825-7.1.6]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1156) [dh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2825-7.1.6]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlk000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

**Comment by jul-fls** [comment]
I have exactly this problem

**Comment by X-Niter** [comment]
Same here

**Comment by X-Niter** [comment]
Looks like he might need to update is plugin for the newer API's.

**Comment by X-Niter** [comment]
His*

**Comment by rodel77** [comment]
Hello! I made a fork fixing this issue, also compiled a temporal jar until the author wants to accept the PR #23: https://github.com/rodel77/UniversalMarket/releases/tag/1.4

**Comment by jul-fls** [comment]
Cool thank you for your contribution but i will not be able to feedback you because i'm using another plugin to do that...
